name: cicd
on:
  workflow_dispatch:
  push:
    branches:
      - master 

permissions:
  id-token: write   
  contents: read 

env:
  BUILD_DIR: "public"
  BUCKET_NAME: "bastienmaurice.fr"

jobs: 
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11.4
          architecture: x64
      - run: pip3 install -r ./requirements.txt
      - run: mkdocs build
      - uses: actions/cache/save@v3
        id: website
        with:
          path: ./${{ env.BUILD_DIR }}
          key: test

  deploy:
    runs-on: ubuntu-22.04
    needs: build
    if:  ${{ github.ref_name == 'master' || github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: actions/cache/restore@v3
        id: website
        with:
          path: ./${{ env.BUILD_DIR }}
          key: test
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::288002323060:role/github-actions-assume-role-access
          aws-region: eu-west-3
          role-session-name: githubactions
      - run: aws s3 sync --delete ${{ github.workspace }}/${{ env.BUILD_DIR }} s3://${{ env.BUCKET_NAME }}/
